# Generated by Django 4.1.6 on 2023-03-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_product_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.JSONField(blank=True, null=True, verbose_name='list of products'),
        ),
    ]
