# Generated by Django 4.2 on 2023-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_available'),
        ('order', '0003_order_product_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', models.JSONField(blank=True, null=True, verbose_name='list of products')),
                ('paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='products.productmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
