# Generated by Django 4.2 on 2023-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordermodel_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='paid',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='amount_paid',
            field=models.FloatField(default=0, verbose_name='amount paid so far'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='finished_payment',
            field=models.BooleanField(default=False, verbose_name='has finished payment'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='product_list',
            field=models.JSONField(default=dict, verbose_name='list of products'),
        ),
    ]
