# Generated by Django 4.2 on 2023-05-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_ordermodel_paid_ordermodel_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='finished_payment',
        ),
    ]
