# Generated by Django 4.2 on 2023-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_ordermodel_finished_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='is paid for'),
        ),
    ]
