# Generated by Django 4.1.6 on 2023-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name of collection')),
                ('number_of_recipes', models.IntegerField()),
                ('descript', models.TextField(verbose_name='description of the collection')),
                ('recipes', models.ManyToManyField(blank=True, null=True, to='recipe.recipemodel')),
            ],
        ),
    ]
