# Generated by Django 4.1.6 on 2023-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='recipe.recipemodel'),
        ),
    ]
