# Generated by Django 4.1.6 on 2023-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collectionmodel_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='number_of_recipes',
            field=models.IntegerField(default=0),
        ),
    ]
