# Generated by Django 4.2 on 2023-05-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collectionmodel_number_of_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='number_of_recipes',
        ),
    ]
