# Generated by Django 4.2 on 2023-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_collectionmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
