# Generated by Django 4.2 on 2023-05-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_collectionmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='photo of collection'),
        ),
    ]
