# Generated by Django 4.1.6 on 2023-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
