# Generated by Django 4.2 on 2023-05-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='photo of product'),
        ),
    ]
