# Generated by Django 4.1.6 on 2023-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name of recipe')),
                ('origin', models.CharField(max_length=50, verbose_name='country of origin')),
                ('calories_ps', models.IntegerField(verbose_name='calories per serving')),
                ('difficulty', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='difficulty level')),
                ('recipe_book', models.TextField()),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.productmodel')),
            ],
        ),
    ]
