# Generated by Django 4.1.6 on 2023-03-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_name'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.productmodel'),
        ),
    ]
