# Generated by Django 4.1.6 on 2023-03-17 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipemodel_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 14, 20, 29, 672955, tzinfo=datetime.timezone.utc)),
        ),
    ]
