# Generated by Django 4.2 on 2023-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipemodel_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='difficulty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='difficulty level'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.JSONField(default=list, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='country of origin'),
        ),
    ]
