# Generated by Django 4.2 on 2023-05-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipemodel_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='intro',
            field=models.TextField(blank=True, verbose_name='introductory note'),
        ),
    ]
